import { createHash } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import {
  HeadroomOptimizer,
  type TokenOptimizer
} from "@atacredits/token-optimizer";
import {
  formatUsdFromCents,
  previewText,
  type EstimateRequest,
  type EstimateResponse,
  type RequestHistoryResponse,
  type SponsoredRequestPayload,
  type SponsoredRequestResponse
} from "@atacredits/shared";
import {
  privacySafePromptMetadata,
  privacySafePromptPreview,
  privacySafeResponsePreview
} from "./privacyLogging.js";
import { buildEstimateResponse, estimateCostCents } from "./requestEstimator.js";
import { SponsoredGatewayClient } from "./sponsoredGateway.js";
import { WalletService } from "./walletService.js";

export class InsufficientSponsoredCreditsError extends Error {
  constructor(public readonly estimate: EstimateResponse) {
    super("INSUFFICIENT_SPONSORED_CREDITS");
  }
}

function hashPrompt(prompt: string): string {
  return createHash("sha256").update(prompt).digest("hex").slice(0, 16);
}

function buildMockResponse(prompt: string, route: "sponsored" | "official"): string {
  const preview = previewText(prompt, 180);
  return [
    route === "sponsored"
      ? "Sponsored gateway response generated by the local MVP."
      : "Official route response generated outside the sponsored gateway.",
    "",
    "Prompt summary:",
    preview,
    "",
    "Suggested next step:",
    "Turn this into a focused implementation plan with explicit acceptance criteria."
  ].join("\n");
}

export class AiService {
  private readonly optimizer: TokenOptimizer;
  private readonly sponsoredGateway: SponsoredGatewayClient;

  constructor(
    private readonly prisma: PrismaClient,
    private readonly walletService: WalletService,
    private readonly sponsoredGatewayModel: string,
    optimizer?: TokenOptimizer
  ) {
    this.optimizer = optimizer ?? new HeadroomOptimizer();
    this.sponsoredGateway = new SponsoredGatewayClient(this.sponsoredGatewayModel);
  }

  async estimate(userId: string, input: EstimateRequest): Promise<EstimateResponse> {
    const [settings, wallet] = await Promise.all([
      this.walletService.getSettings(userId),
      this.walletService.getWallet(userId)
    ]);
    const optimizationMode = input.mode ?? settings.tokenOptimizationMode;
    const optimized = await this.optimizer.optimize(
      {
        prompt: input.prompt,
        model: input.model
      },
      optimizationMode
    );
    return buildEstimateResponse({
      optimized,
      availableCreditsCents: wallet.availableCreditsCents,
      availableCreditsUsd: wallet.availableCreditsUsd,
      optimizationMode,
      minSponsoredBalanceCents: settings.minSponsoredBalanceCents,
      safetyMarginPercent: settings.safetyMarginPercent,
      maxSponsoredCostPerRequestCents: settings.maxSponsoredCostPerRequestCents
    });
  }

  async sponsoredRequest(
    userId: string,
    input: SponsoredRequestPayload
  ): Promise<SponsoredRequestResponse> {
    const estimate = await this.estimate(userId, input);
    if (estimate.route !== "sponsored") {
      await this.prisma.aiRequest.create({
        data: {
          userId,
          route: "OFFICIAL",
          status: "REJECTED",
          model: input.model ?? this.sponsoredGatewayModel,
          promptDigest: hashPrompt(input.prompt),
          promptPreview: privacySafePromptPreview(),
          responsePreview: "Sponsored routing rejected due to insufficient credits.",
          metadataJson: privacySafePromptMetadata(input.prompt),
          originalTokens: estimate.originalTokens,
          optimizedTokens: estimate.optimizedTokens,
          estimatedCostCents: estimate.estimatedCostCents,
          reservedCostCents: 0,
          actualCostCents: 0
        }
      });
      throw new InsufficientSponsoredCreditsError(estimate);
    }

    const request = await this.prisma.aiRequest.create({
      data: {
        userId,
        route: "SPONSORED",
        status: "PROCESSING",
        model: input.model ?? this.sponsoredGatewayModel,
        promptDigest: hashPrompt(input.prompt),
        promptPreview: privacySafePromptPreview(),
        metadataJson: privacySafePromptMetadata(input.prompt),
        originalTokens: estimate.originalTokens,
        optimizedTokens: estimate.optimizedTokens,
        estimatedCostCents: estimate.estimatedCostCents,
        reservedCostCents: estimate.requiredBalanceCents,
        actualCostCents: 0
      }
    });

    await this.walletService.reserveSponsoredCredits({
      userId,
      aiRequestId: request.id,
      amountCents: estimate.requiredBalanceCents
    });

    try {
      const gatewayResponse = await this.sponsoredGateway.run({
        prompt: input.prompt,
        model: input.model
      });
      const text = gatewayResponse.text;
      const actualCostCents = Math.max(
        2,
        Math.min(estimate.estimatedCostCents, Math.ceil(estimate.optimizedTokens / 900))
      );
      const refundedCents = Math.max(0, estimate.requiredBalanceCents - actualCostCents);

      await this.walletService.captureSponsoredCredits({
        userId,
        aiRequestId: request.id,
        amountCents: actualCostCents
      });
      await this.walletService.refundSponsoredCredits({
        userId,
        aiRequestId: request.id,
        amountCents: refundedCents
      });

      await this.prisma.aiRequest.update({
        where: { id: request.id },
        data: {
          status: "SUCCESS",
          responsePreview: privacySafeResponsePreview(text),
          actualCostCents
        }
      });

      return {
        route: "sponsored",
        requestId: request.id,
        model: gatewayResponse.model,
        text,
        originalTokens: estimate.originalTokens,
        optimizedTokens: estimate.optimizedTokens,
        estimatedCostCents: estimate.estimatedCostCents,
        actualCostCents,
        refundedCents,
        wallet: await this.walletService.getWallet(userId)
      };
    } catch (error) {
      await this.walletService.refundSponsoredCredits({
        userId,
        aiRequestId: request.id,
        amountCents: estimate.requiredBalanceCents
      });
      await this.prisma.aiRequest.update({
        where: { id: request.id },
        data: {
          status: "FAILED",
          responsePreview: error instanceof Error ? error.message : "Unknown failure"
        }
      });
      throw error;
    }
  }

  async logOfficialRequest(input: {
    userId: string;
    prompt: string;
    model: string;
    responseText: string;
    estimate: EstimateResponse;
  }): Promise<void> {
    await this.prisma.aiRequest.create({
      data: {
        userId: input.userId,
        route: "OFFICIAL",
        status: "SUCCESS",
        model: input.model,
        promptDigest: hashPrompt(input.prompt),
        promptPreview: privacySafePromptPreview(),
        responsePreview: privacySafeResponsePreview(input.responseText),
        metadataJson: privacySafePromptMetadata(input.prompt),
        originalTokens: input.estimate.originalTokens,
        optimizedTokens: input.estimate.optimizedTokens,
        estimatedCostCents: input.estimate.estimatedCostCents,
        reservedCostCents: 0,
        actualCostCents: 0
      }
    });
  }

  async getHistory(userId: string): Promise<RequestHistoryResponse> {
    const items = await this.prisma.aiRequest.findMany({
      where: { userId },
      orderBy: { createdAt: "desc" },
      take: 20
    });

    return {
      items: items.map((item) => ({
        id: item.id,
        route: item.route === "SPONSORED" ? "sponsored" : "official",
        status: item.status,
        model: item.model,
        promptPreview: item.promptPreview,
        responsePreview: item.responsePreview ?? "",
        estimatedCostCents: item.estimatedCostCents,
        estimatedCostUsd: formatUsdFromCents(item.estimatedCostCents),
        actualCostCents: item.actualCostCents,
        actualCostUsd: formatUsdFromCents(item.actualCostCents),
        originalTokens: item.originalTokens,
        optimizedTokens: item.optimizedTokens,
        createdAt: item.createdAt.toISOString()
      }))
    };
  }

  buildOfficialResponse(prompt: string): { text: string; model: string } {
    return {
      text: buildMockResponse(prompt, "official"),
      model: "local-official-demo"
    };
  }
}
