export class SponsoredGatewayClient {
  constructor(private readonly defaultModel: string) {}

  async run(input: {
    prompt: string;
    model?: string;
  }): Promise<{ model: string; text: string }> {
    await new Promise((resolve) => setTimeout(resolve, 900));
    return {
      model: input.model ?? this.defaultModel,
      text: [
        "Sponsored gateway response generated by the local MVP.",
        "",
        "Prompt summary:",
        input.prompt.replace(/\s+/g, " ").trim().slice(0, 180),
        "",
        "Suggested next step:",
        "Turn this into a focused implementation plan with explicit acceptance criteria."
      ].join("\n")
    };
  }
}
